import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neueMachina = localFont({
  src: [
    {
      path: "../public/fonts/neue-machina/PPNeueMachina-PlainLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/neue-machina/PPNeueMachina-PlainRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/neue-machina/PPNeueMachina-PlainMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/neue-machina/PPNeueMachina-PlainSemibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/neue-machina/PPNeueMachina-PlainBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--w4-font-heading",
  display: "swap",
});

const raleway = localFont({
  src: [
    {
      path: "../public/fonts/raleway/Raleway-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/raleway/Raleway-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/raleway/Raleway-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--w4-font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl" className={`${neueMachina.variable} ${raleway.variable}`}>
      <body>{children}</body>
    </html>
  );
}
